/*
    dro2hdr.c — convert a DOSBox DRO v2 capture into a C header file
    containing  static const opl_song songname  ready to embed in
    microcontroller flash.

    The packed `opl_song` format is byte-compatible with the DRO v2
    payload (codemap + (code,val) opcode stream), so this tool is
    essentially a verbatim dump of the relevant bytes wrapped in C
    syntax.  ~2 bytes per register write versus ~6 bytes for the older
    opl_event[] format.

    Usage:
       dro2hdr input.dro output.h song_symbol_name

    Offline tool — not part of the MCU build.
*/
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static int
read_u32(FILE* f, uint32_t* o)
{
	uint8_t b[4];

	if (fread(b, 1, 4, f) != 4)
		return -1;

	*o = (uint32_t)b[0] | ((uint32_t)b[1] << 8) |
		 ((uint32_t)b[2] << 16) | ((uint32_t)b[3] << 24);
	return 0;
}

int
main(int argc, char** argv)
{
	if (argc != 4) {
		fprintf(stderr, "usage: %s in.dro out.h symbol\n", argv[0]);
		return 1;
	}

	const char* in_path  = argv[1];
	const char* out_path = argv[2];
	const char* sym      = argv[3];

	FILE* f = fopen(in_path, "rb");

	if (!f) {
		perror(in_path);
		return 1;
	}

	char m[8];
	uint32_t v, lp, lm;
	uint8_t hdr[5], cmLen, cm[256] = {0};

	if (fread(m, 1, 8, f) != 8 || memcmp(m, "DBRAWOPL", 8) ||
		read_u32(f, &v) || read_u32(f, &lp) || read_u32(f, &lm) || v != 2) {
		fprintf(stderr, "%s: not a DRO v2 file\n", in_path);
		fclose(f);
		return 2;
	}

	if (fread(hdr, 1, 5, f) != 5) {
		fclose(f);
		return 3;
	}

	uint8_t sc = hdr[3], lc = hdr[4];

	if (fread(&cmLen, 1, 1, f) != 1) {
		fclose(f);
		return 4;
	}

	if (cmLen && fread(cm, 1, cmLen, f) != cmLen) {
		fclose(f);
		return 5;
	}

	uint8_t* raw = malloc((size_t)lp * 2);

	if (!raw || fread(raw, 1, (size_t)lp * 2, f) != (size_t)lp * 2) {
		fprintf(stderr, "%s: short read\n", in_path);
		free(raw);
		fclose(f);
		return 7;
	}

	fclose(f);

	/*  Build the packed payload: codemap bytes followed by the raw
	    (code,val) opcode stream.  This is identical to what
	    seq_player's MODE_PACKED decoder consumes. */
	size_t total = (size_t)cmLen + (size_t)lp * 2;
	uint8_t* out = malloc(total);
	memcpy(out, cm, cmLen);
	memcpy(out + cmLen, raw, (size_t)lp * 2);
	free(raw);

	FILE* g = fopen(out_path, "w");

	if (!g) {
		perror(out_path);
		free(out);
		return 8;
	}

	fprintf(g,
			"/* Auto-generated by tools/dro2hdr from %s.\n"
			" * Packed (opl_song) format: ~2 bytes per OPL register write.\n"
			" * Register writes : %u\n"
			" * Total length    : %u ms (%.1f s)\n"
			" * Payload size    : %zu bytes (codemap=%u + stream=%u)\n"
			" * Do not edit.\n"
			" */\n"
			"#ifndef %s_H\n#define %s_H\n\n"
			"#include \"seq_player.h\"\n\n"
			"static const uint8_t %s_data[] = {\n   ",
			in_path, lp, lm, lm / 1000.0,
			total, cmLen, lp * 2,
			sym, sym, sym);

	for (size_t i = 0; i < total; i++) {
		fprintf(g, " 0x%02X,", out[i]);

		if ((i & 15) == 15)
			fputs("\n   ", g);
	}

	if ((total & 15) != 0)
		fputc('\n', g);

	fprintf(g,
			"};\n\n"
			"static const opl_song %s = {\n"
			"    .data        = %s_data,\n"
			"    .data_len    = sizeof(%s_data),\n"
			"    .codemap_len = %u,\n"
			"    .short_code  = 0x%02X,\n"
			"    .long_code   = 0x%02X,\n"
			"    .total_ms    = %uu,\n"
			"};\n\n"
			"#endif\n",
			sym, sym, sym, cmLen, sc, lc, lm);

	fclose(g);

	printf("Wrote %s: %u register writes, %u ms, %zu bytes payload (~%.1f KB).\n",
		   out_path, lp, lm, total, total / 1024.0);
	free(out);
	return 0;
}
