/*
    dro2hdr.c — convert a DOSBox DRO v2 capture into a C header file
    containing  static const opl_event songname[]  ready to embed in
    microcontroller flash.

    Usage:
       dro2hdr input.dro output.h song_symbol_name

    Offline tool — not part of the MCU build.
*/
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static int
read_u32(FILE* f, uint32_t* o)
{
	uint8_t b[4];

	if (fread(b, 1, 4, f) != 4)
		return -1;

	*o = (uint32_t)b[0] | ((uint32_t)b[1] << 8) |
		 ((uint32_t)b[2] << 16) | ((uint32_t)b[3] << 24);
	return 0;
}

int
main(int argc, char** argv)
{
	if (argc != 4) {
		fprintf(stderr, "usage: %s in.dro out.h symbol\n", argv[0]);
		return 1;
	}

	const char* in_path  = argv[1];
	const char* out_path = argv[2];
	const char* sym      = argv[3];

	FILE* f = fopen(in_path, "rb");

	if (!f) {
		perror(in_path);
		return 1;
	}

	char m[8];
	uint32_t v, lp, lm;
	uint8_t hdr[5], cmLen, cm[256] = {0};

	if (fread(m, 1, 8, f) != 8 || memcmp(m, "DBRAWOPL", 8) ||
		read_u32(f, &v) || read_u32(f, &lp) || read_u32(f, &lm) || v != 2) {
		fprintf(stderr, "%s: not a DRO v2 file\n", in_path);
		fclose(f);
		return 2;
	}

	if (fread(hdr, 1, 5, f) != 5) {
		fclose(f);
		return 3;
	}

	uint8_t sc = hdr[3], lc = hdr[4];

	if (fread(&cmLen, 1, 1, f) != 1) {
		fclose(f);
		return 4;
	}

	if (cmLen && fread(cm, 1, cmLen, f) != cmLen) {
		fclose(f);
		return 5;
	}

	uint8_t* raw = malloc((size_t)lp * 2);

	if (!raw) {
		fclose(f);
		return 6;
	}

	if (fread(raw, 1, (size_t)lp * 2, f) != (size_t)lp * 2) {
		fprintf(stderr, "%s: short read\n", in_path);
		free(raw);
		fclose(f);
		return 7;
	}

	fclose(f);

	/*  Decode into (reg, val, delay_after_ms) triples, exactly the
	    shape of opl_event. */
	typedef struct {
		uint16_t reg;
		uint8_t val;
		uint32_t delay_ms;
	} E;
	E* ev = malloc(sizeof(E) * lp);
	size_t nev = 0;

	for (uint32_t i = 0; i < lp; i++) {
		uint8_t c = raw[i * 2], val = raw[i * 2 + 1];

		if (c == sc) {
			if (nev)
				ev[nev - 1].delay_ms += (uint32_t)val + 1;

		} else if (c == lc) {
			if (nev)
				ev[nev - 1].delay_ms += ((uint32_t)val + 1) * 256u;

		} else {
			uint8_t idx = c & 0x7F;

			if (idx >= cmLen)
				continue;

			ev[nev].reg      = cm[idx] | ((c & 0x80) ? 0x100 : 0);
			ev[nev].val      = val;
			ev[nev].delay_ms = 0;
			nev++;
		}
	}

	free(raw);

	/*  Split any delay > 65535 ms across extra dummy events (re-write
	    the same register with the same value, harmless) so that the
	    delay_ms field of opl_event (uint16_t) is sufficient. */
	size_t cap = nev * 2 + 16;
	E* ev2 = malloc(sizeof(E) * cap);
	size_t nev2 = 0;

	for (size_t i = 0; i < nev; i++) {
		E e = ev[i];

		while (e.delay_ms > 65535u) {
			E split = e;
			split.delay_ms = 65535u;
			ev2[nev2++] = split;
			e.delay_ms -= 65535u;
			/* dummy continuation: a no-op write; reuse same reg/val */
			E noop = { e.reg, e.val, 0 };
			ev2[nev2++] = noop;
		}

		ev2[nev2++] = e;
	}

	free(ev);

	uint32_t total_ms = 0;

	for (size_t i = 0; i < nev2; i++)
		total_ms += ev2[i].delay_ms;

	FILE* g = fopen(out_path, "w");

	if (!g) {
		perror(out_path);
		free(ev2);
		return 8;
	}

	fprintf(g,
			"/* Auto-generated by tools/dro2hdr from %s.\n"
			" * Total events : %zu\n"
			" * Total length : %u ms (%.1f s)\n"
			" * Original DRO : %u ms\n"
			" * Do not edit.\n"
			" */\n"
			"#ifndef %s_H\n#define %s_H\n\n"
			"#include \"seq_player.h\"\n\n"
			"static const opl_event %s[] = {\n",
			in_path, nev2, total_ms, total_ms / 1000.0, lm, sym, sym, sym);

	for (size_t i = 0; i < nev2; i++) {
		fprintf(g, "    {0x%03X,0x%02X,%5u},",
				ev2[i].reg, ev2[i].val, ev2[i].delay_ms);

		if ((i & 3) == 3)
			fputc('\n', g);
	}

	if (nev2 & 3)
		fputc('\n', g);

	fprintf(g,
			"};\n\n"
			"#define %s_count ((uint32_t)(sizeof(%s)/sizeof(%s[0])))\n"
			"#define %s_total_ms %uu\n\n"
			"#endif\n",
			sym, sym, sym, sym, total_ms);

	fclose(g);
	free(ev2);

	/* sizeof(opl_event) is 6 on most ABIs (uint16+uint8+uint16, padded). */
	printf("Wrote %s: %zu events, %u ms (~%.1f KB of flash).\n",
		   out_path, nev2, total_ms, nev2 * 6.0 / 1024.0);
	return 0;
}
